name: build
on:
  push:
    branches: [ master, dev ]
    paths: ['**.h', '**.c']

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make re CC=/bin/gcc
    - run: make re CC=/bin/clang
