name: build
on:
  push:
    branches: [ master, dev ]
    paths: ['**.h', '**.c']

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: CC=/bin/gcc make re
    - run: CC=/bin/clang CFLAGS=-Weverything make re
