name: build
on:
  push:
    branches: [ master, dev ]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make re CC=/bin/gcc
    - run: make re CC=/bin/clang
