name: lint
on:
  push:
    branches: [ master, dev ]
    paths: ['**.h', '**.c']

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y clang-tidy cppcheck pip
    - run: sudo pip install cpplint
    - run: make lint
