name: lint
on:
  push:
    branches: [ master, dev ]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y cppcheck clang-tidy pip
    - run: sudo pip install cpplint
    - run: make lint
